#!/usr/bin/python

from __future__ import print_function
import shutil
import os

import canros
import uavcan

def print_type(typ, file=None):
	if typ.category == typ.CATEGORY_PRIMITIVE:
		if typ.kind == typ.KIND_BOOLEAN:
			print("bool", end='', file=file)
		elif typ.kind == typ.KIND_FLOAT:
			if typ.bitlen <= 32:
				print("float32", end='', file=file)
			else:
				print("float64", end='', file=file)
		else:
			if typ.kind == typ.KIND_UNSIGNED_INT:
				print("u", end='', file=file)
			if typ.bitlen <= 8:
				print("int8", end='', file=file)
			elif typ.bitlen <= 16:
				print("int16", end='', file=file)
			elif typ.bitlen <= 32:
				print("int32", end='', file=file)
			else:
				print("int64", end='', file=file)

	elif typ.category == typ.CATEGORY_COMPOUND:
		print(canros.ros_name(typ.full_name), end='', file=file)

	elif typ.category == typ.CATEGORY_ARRAY:
		print_type(typ.value_type, file=file)
		print("[]", sep='', end='', file=file)

def print_constant(const, file=None):
	print_type(const.type, file=file)
	print(" ", const.name, "=", const.value, sep='', file=file)

def print_field(field, file=None):
	print_type(field.type, file=file)
	print(" ", field.name, sep='', file=file)

def print_id(file=None):
	id_tag_type = uavcan.dsdl.parser.PrimitiveType(
		uavcan.dsdl.parser.PrimitiveType.KIND_UNSIGNED_INT,
		7,
		uavcan.dsdl.parser.PrimitiveType.CAST_MODE_SATURATED
	)

	print("\n# UAVCAN ID field", file=file)
	print_field(uavcan.dsdl.parser.Field(id_tag_type, canros.uavcan_id_field_name), file=file)

def print_union(fields, file=None):
	union_tag_type = uavcan.dsdl.parser.PrimitiveType(
		uavcan.dsdl.parser.PrimitiveType.KIND_UNSIGNED_INT,
		len(fields),
		uavcan.dsdl.parser.PrimitiveType.CAST_MODE_SATURATED
	)

	print("\n# Union field selector tag", file=file)

	for i in range(0, len(fields)):
		print_constant(uavcan.dsdl.parser.Constant(
			union_tag_type,
			canros.union_const_prefix + fields[i].name.upper(),
			str(i), i
		), file=file)

	print_field(uavcan.dsdl.parser.Field(union_tag_type, canros.union_tag_field_name), file=file)

def print_msg(constants, fields, union, file=None):
	for const in constants:
		if const.type.category == const.type.CATEGORY_VOID:
			continue
		print_constant(const, file=file)

	for field in fields:
		if field.type.category == field.type.CATEGORY_VOID:
			continue
		print_field(field, file=file)

	if union:
		print_union(fields, file=file)

def print_header(rows, file=None):
	maxlen = max([len(row) for row in rows])
	horz_bar = "#"*(maxlen+6)
	print(horz_bar, file=file)
	for row in rows:
		print("# ", row, " "*(maxlen-len(row)), "#", file=file)
	print(horz_bar, "\n", sep='', file=file)

def make_rel_dir(dir):
	canros_dir = os.path.dirname(os.path.dirname(__file__))
	abs_dir = os.path.join(canros_dir, dir)
	if os.path.exists(abs_dir):
		shutil.rmtree(abs_dir)
	os.makedirs(abs_dir)
	return abs_dir

def main():
	ros_msg_dir = make_rel_dir("msg")
	ros_srv_dir = make_rel_dir("srv")

	for _, typ in uavcan.TYPENAMES.items():
		if typ.kind == typ.KIND_MESSAGE:
			file_path = os.path.join(ros_msg_dir, canros.ros_name(typ.full_name) + ".msg")
		else:
			file_path = os.path.join(ros_srv_dir, canros.ros_name(typ.full_name) + ".srv")

		with open(file_path, 'w+') as f:
			print_header(["Generated by canros", typ.full_name], file=f)

			if typ.kind == typ.KIND_MESSAGE:
				print_msg(typ.constants, typ.fields, typ.union, file=f)
				if canros.ros_has_id_field(typ.full_name):
					print_id(file=f)
			elif typ.kind == typ.KIND_SERVICE:
				print_msg(typ.request_constants, typ.request_fields, typ.request_union, file=f)
				print_id(file=f)
				print("---", file=f)
				print_msg(typ.response_constants, typ.response_fields, typ.response_union, file=f)

if __name__ == "__main__":
	main()
